### ISSUE TITLE
Port of FSharp.Formatting.Markdown?

### ISSUE THREAD

**Issue by davedawkins** [MangelMaxime/Fable.Markdown#1]
Hi,
is this a port of FSharp.Formatting.Markdown? 

I should have checked first, but I've ported the Markdown component from FSharp.Formatting.Markdown to Fable, and was planning to make it available, but I don't want to add noise to the package-scape if it's already been done.

Cheers

**Comment by MangelMaxime** [comment]
Hello @davedawkins ,

right now I think this repository does nothing. 

But there is a plan to have Fable markdown parser in the future when I will have written my generic parser library so I can use it for Thoth.Json, Thoth.Xml (doesn't exist yet), etc.

So in theory you are ahead of me :wink:

**Comment by davedawkins** [comment]
Hi @MangelMaxime ,
OK :-)

Here's my example Fable program, followed by a screenshot of output:

```fsharp

let markdown md =
    let doc = FSharp.Formatting.Markdown.Markdown.Parse(md)
    FSharp.Formatting.Markdown.Markdown.ToHtml(doc)

let appE = Browser.Dom.window.document.querySelector("#app")

appE.innerHTML <- markdown markdownSrc
```

Input:
```
let markdownSrc = """
##Markdown Example

This is *italic*, and this is **bold**, and this is a `symbol`.

**Unordered List**

- Unordered item
- Next item
- Last item

**Numbered List**

1. First step
1. Second step
1. Third step

**Code**

    let fib n =
        if n <= 1 then
            1
        else
            n * (fib (n-1)) 

"""
```

<img width="349" alt="image" src="https://user-images.githubusercontent.com/285421/128776268-184b4644-ff65-424b-bde5-085d18051b88.png">

Is there a way for me to publish this (to github and nuget) that fits in with your plans? 

It's effectively a fork of FSharp.Formatting, but only the Markdown module and dependencies. I was considering publishing it as Fable.Markdown, but this doesn't match the interal namespace/module names. I guess it could be Fable.Formatting.Markdown, and perhaps do a global rename of the classes...??

Advice appreciated.

Update: I renamed the classes and modules to be "Fable.Formatting...". In theory this can co-exist with anything you release in the future named "Fable.Markdown", although I hope this code will be of use. I'll be happy to merge the two projects into a single project (or use yours) at that point.

Cheers

**Comment by davedawkins** [comment]
Link to repo here:
https://github.com/davedawkins/Fable.Formatting.Markdown

**Comment by MangelMaxime** [comment]
Hello @davedawkins,

sorry for the delay, I am still on vacation so I don't always have internet access :)

That is really cool that you where able to released your package. Fable.Formatting... seems a good name as it keeps the link/history with FSharp.Formatting.

My vision for my project is to allow people to apply changed to the AST or extends with a plugin. We will see if we can merge both project or have them separately because they solve different issues.

In any case, I would be happy to discuss it when I have a working prototype of mine. 

One benefit of having yours as a direct port of FSharp.Formatting is that parser has the same capabilities and limitations. For exemple, I found out that FSharp.Formatting isn't 100% compliant with Markdown sepcs. In fact, it is pretty hard and rare to be 100% compliant because the spec is not always deterministic at least the last time I checked.

**Comment by davedawkins** [comment]
That all sounds great. I agree with all your points. In my experience all markdown implementations are different, but I did want to try and preserve whatever the FS community was standardizing on. Another option is to track the github markdown format (several years ago , for my own product I started tracking the Stackoverflow format).

I'm easy with whatever you want to do with your project, and am open to merging if it makes sense.

Enjoy your holiday, and thanks for taking time out to reply - it's very encouraging to have your support.
